sudo: false
language: node_js
node_js:
  - 10
cache: yarn
notifications:
  email: false
after_success:
  - yarn semantic-release
deploy:
  provider: npm
  email: npm@tlvince.com
  skip_cleanup: true
  on:
    branch: master
    repo: tlvince/eslint-config-tlvince
