version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          update_type: "all"
          dependency_type: "all"
    commit_message:
      prefix: "fix"
      include_scope: true
